### PR TITLE
Update data.json(#1)

### PR DESCRIPTION
**Pull request by AK-codingmaniac**
I have added the song Kesariya which is a superhit in 2022. 
Please see to it and merge it as soon as possible for HacktoberFest2022

### CODE REVIEW

**Comment by AK-codingmaniac** [comment]
@sakshieng why didn't this PR get merged?
Is there any issue?

**Comment by sakshieng** [comment]
Yes It has issues
I will merge the PR once I resolve the conflict.

**Comment by AK-codingmaniac** [comment]
Ok @sakshieng I was just concerned regarding HacktoberFest 2022
It was in the waiting state but it also says that PR must be merged in the repo
that's why I asked you

**Comment by sakshieng** [comment]
Done

**Comment by AK-codingmaniac** [comment]
Thank you @sakshieng

**Pull request merged**
